name: moviestar
description: "A modern privacy-first movie discovery and tracking application."
publish_to: "none"
version: 0.0.4+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  file_picker: ^10.1.9
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.14.2
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^10.0.0-beta.4
  # Database dependencies for local caching
  drift: ^2.18.0
  http: ^1.1.0
  intl: ^0.20.2
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.15
  markdown_tooltip: ^0.0.7
  path: ^1.9.1
  pdf: ^3.11.3
  printing: ^5.14.2
  provider: ^6.1.1
  rdflib: ^0.2.12
  rxdart: ^0.28.0
  shared_preferences: ^2.2.2
  solidpod: ^0.6.7
  syncfusion_flutter_pdf: ^30.1.37
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  # Database code generation dependencies
  build_runner: ^2.4.7
  drift_dev: ^2.18.0
  import_order_lint: ^0.1.1
  ubuntu_lints: ^0.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# Define launcher icons for all platforms (except Linux) so icons for
# the apps can be automatically updated using:
#
# `dart run flutter_launcher_icons`
#
# (gjw 20250429)

flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  min_sdk_android: 21
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  macos:
    generate: true
  web:
    generate: true
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
