name: moviestar
description: "A modern privacy-first movie discovery and tracking application."
publish_to: "none"
version: 0.0.2+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  file_picker: ^10.1.9
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^10.0.0-beta.4
  http: ^1.1.0
  intl: ^0.20.2
  markdown_tooltip: ^0.0.7
  path: ^1.9.1
  pdf: ^3.11.3
  printing: ^5.14.2
  provider: ^6.1.1
  rdflib: ^0.2.12
  rxdart: ^0.28.0
  shared_preferences: ^2.2.2
  solidpod: ^0.6.7
  syncfusion_flutter_pdf: ^30.1.37
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  import_order_lint: ^0.1.1
  ubuntu_lints: ^0.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
